
" Make sure Vim Plug is installed
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'rust-lang/rust.vim'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'morhetz/gruvbox'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'powerline/powerline' 

call plug#end()

autocmd vimenter * ++nested colorscheme gruvbox

filetype plugin indent on
syntax on

set background=dark
set number
set mouse=a
set noerrorbells
set tabstop=4 softtabstop=4
set expandtab
set smartindent
set nowrap
set nu
set noswapfile
set nobackup
if !has('nvim')
    set undodir=~/.vim/undodir
else
    set undodir=~/.vim/nvim/undodir
endif
set undofile
set incsearch
set colorcolumn=80
set showtabline=2

" Remap i is up, j is left, k is down, l is right, h is insert
noremap h i
noremap j <Left>
noremap k <Down>
noremap i <Up>

nnoremap <C-j> <C-W><C-H>
nnoremap <C-i> <C-W><C-K>
nnoremap <C-k> <C-W><C-J>
nnoremap <C-l> <C-W><C-L>

inoremap jj <ESC>

" Nerdtree
noremap <C-e> :NERDTreeToggle<CR>
let NERDTreeMapOpenSplit='h'
" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

" New Tabs
noremap <C-t> :tabe<CR>

" Quit file
noremap <C-w> :q<CR>
inoremap <C-w> <ESC>:q<CR>

" Code Completion with coc
source ~/.vim/my_coc.vim

" Set Powerline
if !has('nvim')
    source ~/.vim/plugged/powerline/powerline/bindings/vim/plugin/powerline.vim
endif

